server {
    listen 127.0.0.2:8080;
    listen 127.0.0.2:8888;

    hostname webserv.com;

    root ./www;

    errorPage 404 ./www/default/html/error/404.html;
    errorPage 403 ./www/default/html/error/403.html;
    errorPage 418 ./www/default/html/error/418.html;

    maxSize 20m;

    location / {
        method GET
        index index.html
    }

    location /images {
        method GET
        autoIndex on
    }

    location /upload {
        method GET DELETE POST
        autoIndex on
    }

    location /cgi-bin {
        index cgi-bin.html
        cgi .py /bin/python3
        cgi .sh /bin/bash
        uploadPath ./www/default/upload
        method POST GET
    }

    location /redir {
        return 301 https://github.com/CDRX2/42_webserv/
    }

    location /moved_permanently {
        return 308 https://www.youtube.com/
    }
}
