server {
	hostName prout;
	listen localhost:4242;
	listen localhost:8080;
	errorPage {
		code 400 401 403 404 500 501 502 503 504;
		path /error/;
	}
	maxSize 1024;
	demo {
		protocol HTTP/1.1;
		listDirectory true;
		defaultFile /demo/index.html;
		uploadingFile true;
		root /www/;
	}

	hostName pouet;
	listen default
}
