server {
	maxSize 429496;
	errorPage 400 			     401 404 ./README.md;
	errorPage 401 			     501 504 ./README.md;
	hostname www;
	listen 127.0.0.1:8380;
	danalexian {
		methods GET POST DELETE;
		listDirectory true;
		CGI bruh.py;
		root www/;
		redirection mignon;
		defaultFile index.html;
		uploadingFile false;
		}
	}
