server {
	maxSize 4294967297;
	errorPage 400 			     401 404 ./README.md;
	errorPage 401 			     501 504 ./README.md;
	hostname hii;
	listen 1.15.126.0:8080;
	caca {
		methods GET GET GET GET DELETE;
		listDirectory true;
		CGI bruh.py;
		root www;
		redirection matesticule.fr www.matesticulegauche.com;
		defaultFile ./test.conf;
		uploadingFile false;
		}
	}
