server {
	maxSize 4294967297;
	errorPage 400 			     401 404 ./README.md;
	errorPage 401 			     501 504 ./README.md;
	hostname hii;
	listen :;
	caca {
		methods GET GET GET GET DELETE;
		listDirectory true;
		CGI .py;
		root ;
		redirection matesticule.fr www.matesticulegauche.com;
		defaultFile ./test.conf;
		uploadingFile false;
		}
	}
