server {
	maxSize -2000;
	errorPage -400 			     401 404 ./README.md;
	hostname ;
	listen :;
	caca {
		methods GET GET GET GET DELETE;
		listDirectory true;
		CGI dkasjdisajdi;
		root ;
		redirection matesticule.fr www.matesticulegauche.com;
		defaultFile ./test.conf;
		uploadingFile false;
		}
	}
