server {
	maxSize 200000;
	errorPage 400 ./README.md;
	errorPage  400 501 502 599 ./test.conf;
	hostname caca;
	listen localhost:2020;
	listen Pipo:6969;
	caca {
		methods GET POST DELETE;
		listDirectory true;
		CGI /path/of/moncul.py;
		root /cscs/pipou;
		redirection www.matesticulegauche.com caca.pipi;
		defaultFile ./test.conf;
		uploadingFile false;
		}
	test {
		methods GET DELETE POST POST POST POST;
		listDirectory true;
		CGI .py;
		redirection ww.;
		root ;
		defaultFile ./test.conf;
		uploadingFile false;
		}
	}
