server {
	listen 127.0.0.1:8080
	listen 127.69.69.69:6969
	listen 127.0.0.2:8080
	listen 127.0.0.2:8888

	hostname webserv.com

	root ./www/danalexian

	errorPage 404 ./www/danalexian/error/404.html
	errorPage 403 ./www/danalexian/error/403.html
	errorPage 418 ./www/danalexian/error/418.html

	maxSize 20 m

	location / {
		method GET
		index index.html
	}

	location /uploads {
		autoIndex on
		method DELETE POST GET
	}

	location /uploads/test {
			autoIndex on
			method POST DELETE
		}

	location /cgi-bin {
		index cgi.py
		cgi .py /bin/python3
		cgi .sh /bin/bash
		uploadPath ./www/default/upload
		method POST GET
	}

	location /moved_permanently {
		return 301 https://pedantix.certitudes.org/
	}

	location /temporary_redirect {
		return 307 https://youtu.be/Aq5WXmQQooo?si=tI6V2wrSeiouqS35
	}

	location /permanent_redirect {
		return 308 https://www.youtube.com/
	}
}
